### PR TITLE
Update windows native libraries

### PR DESCRIPTION
**Pull request by peppy**
Taken from https://buildbot.libsdl.org/sdl-builds/

I tried to setup action-based building of this but the effort overhead is too large for now. Have tested (64-bit only) on windows.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Which build is this actually using? Between the build listed on the releases page (https://www.libsdl.org/download-2.0.php), the build on buildbot (sdl-visualstudio-amd64), and the build in this PR, I have 3 different files:

image

**Comment by smoogipoo** [comment]
Looks like the one on the releases page is still 2.0.12 so I suppose it's old, but I'm still wondering about where the discrepancy between the PR one and the buildbot one comes from.

**Comment by peppy** [comment]
It seems to build every commit. I used `202` builds for both x86 and x64

**Comment by smoogipoo** [comment]
Awesome, just making sure :)

**Pull request merged**
