### PR TITLE
Fix Github Action build

### PR DESCRIPTION
**Pull request by Thog**
This fix github actions build issues since SDL migration to github.

### CODE REVIEW

**Comment by Thog** [comment]
Not needed anymore as of eb4e0cbe50868fc066bc81eb5c0936bd3bcb13c3 :+1:

**Comment by peppy** [comment]
Thanks for the PR here (almost missed it as I somehow wasn't watching the repository).

I've merged the upstream changes in from `SDL2-CS`, which causes quite a few conflicts with your local updates in `SDL2.cs`. If possible, I'd like to minimise the divergence we make from the upstream project, so where feasible I think your changes should be replaced by the upstream ones.

If possible, can you take a look at the conflicts currently occurring in that file? I am willing to go through this myself but you may find it qui--------------

**Comment by peppy** [comment]
We actually still need this PR for a few reasons:

- You've fixed the github actions which we rely on.
- You've added some hints which aren't actually present in upstream (for undetermined reasons)

Did you want to look at resolving the conflicts or opening a new PR with just the remaining required portions if possible?

Also I'm curious how you went about this update - the changes you made seem slightly different than the upstream ones. Did you do this manually or via some automated process that doesn't match what was done upstream somehow?

**Comment by Thog** [comment]
> We actually still need this PR for a few reasons:
> 
>     * You've fixed the github actions which we rely on.
> 
>     * You've added some hints which aren't actually present in upstream (for undetermined reasons)
> 
> 
> Did you want to look at resolving the conflicts or opening a new PR with just the remaining required portions if possible?
> 
> Also I'm curious how you went about this update - the changes you made seem slightly different than the upstream ones. Did you do this manually or via some automated process that doesn't match what was done upstream somehow?

Hi,

Okay will rebase and see what was missing. I did a manual diffing of each headers manually (but still missed some hints and events, will cherry-pick those)

For the CI part, I fixed it but I ended up doing something different for Ryujinx fork.
As the buildbot of SDL is currently dead, I did some automatic GitHub Action that do nightly releases of the SDL repo (see https://github.com/Thog/SDL-CI)

**Comment by peppy** [comment]
As an aside, it might be worth PRing the missing hints etc. upstream, as (apart from the lack of nuget packaging) it still seems to be well maintained.

Would appreciate the build script updates here though - was planning on getting a new nuget release out today :).

**Comment by Thog** [comment]
> As an aside, it might be worth PRing the missing hints etc. upstream, as (apart from the lack of nuget packaging) it still seems to be well maintained.
> 
> Would appreciate the build script updates here though - was planning on getting a new nuget release out today :).

Alright, will make a PR and fix this one tonight ^^

**Comment by Thog** [comment]
Ready to review again @peppy 

For the hints changes see https://github.com/flibitijibibo/SDL2-CS/pull/218

**Review by peppy — APPROVED** [review]

**Pull request merged**
