### PR TITLE
Add an Android bindings project

### PR DESCRIPTION
**Pull request by hwsmm**
- Required by https://github.com/ppy/osu-framework/pull/6105

This PR adds an Android bindings project to the repository, and a workflow to build binaries for Android.
I separated it from the original project since building it requires Xamarin, and I thought that most consumers of this project won't like it.

Workflow may need to be run once to replace my binaries.

### CODE REVIEW

**Comment by Susko3** [comment]
Needs a `global.json` that specifies .NET 6, else the `SDL2AndroidBridge.jar` stuff won't properly work (no C# classes, no native libraries in the `.nupkg`). It was trying to build a .NET 6 library with the .NET 8 SDK for me and things broke.

```json
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestFeature"
  }
}
```

**Comment by hwsmm** [comment]
Thanks! I struggled with it yesterday, and I ended up removing .NET 8 on my PC :joy:
I just added global.json and removed SDL2AndroidMainSetter by backporting the commit you mentioned in the framework PR.

**Comment by Susko3** [comment]
The correct place to backport the change is https://github.com/libsdl-org/SDL/tree/SDL2.

**Comment by hwsmm** [comment]
That might be better, but I don't know how to request that politely. It's already implemented in master, and AFAIK SDL2 is in 'maintainence', where new features are only encouraged in SDL3 branch.

We can probably ask SDL devs to cherry-pick the commit to SDL2 branch, but I don't want to do it myself as it doesn't sound so right for me to make them work in the maintainence branch for something we can do ourselves easily.

**Pull request closed without merging**
